local p = require("lush_theme.lavi.palette")
local transforms = require("lush_theme.lavi.transforms")
local helpers = require("shipwright.transform.helpers")

local colors = {
  bg = p.bg,
  fg = p.fg,
  fg_dim = p.fg_dim,
  fg_bright = p.fg_bright,
  cursor_fg = p.cursor_fg,
  cursor_bg = p.cursor_bg,
  blush = p.blush,
  bg_bright = p.bg_bright,
  med_violet = p.med_violet,
  selection_fg = p.selection_fg,
  selection_bg = p.selection_bg,

  black = p.ansi.normal.black,
  red = p.ansi.normal.red,
  green = p.ansi.normal.green,
  yellow = p.ansi.normal.yellow,
  blue = p.ansi.normal.blue,
  magenta = p.ansi.normal.magenta,
  cyan = p.ansi.normal.cyan,
  white = p.ansi.normal.white,

  bright_black = p.ansi.bright.black,
  bright_red = p.ansi.bright.red,
  bright_green = p.ansi.bright.green,
  bright_yellow = p.ansi.bright.yellow,
  bright_blue = p.ansi.bright.blue,
  bright_magenta = p.ansi.bright.magenta,
  bright_cyan = p.ansi.bright.cyan,
  bright_white = p.ansi.bright.white,
}

local template = [[
[colors.primary]
background = "$bg"
foreground = "$fg"
dim_foreground = "$fg_dim"
bright_foreground = "$fg_bright"

[colors.cursor]
text = "$cursor_fg"
cursor = "$cursor_bg"

[colors.vi_mode_cursor]
text = "$cursor_fg"
cursor = "$cursor_bg"

[colors.search.matches]
foreground = "$blush"
background = "$bg"

[colors.search.focused_match]
foreground = "$bg"
background = "$blush"

[colors.footer_bar]
foreground = "$fg"
background = "$bg_bright"

[colors.hints.start]
foreground = "$med_violet"
background = "$bg_bright"

[colors.hints.end]
foreground = "$fg"
background = "$bg_bright"

[colors.selection]
text = "$selection_fg"
background = "$selection_bg"

[colors.normal]
black = "$black"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$white"

[colors.bright]
black = "$bright_black"
red = "$bright_red"
green = "$bright_green"
yellow = "$bright_yellow"
blue = "$bright_blue"
magenta = "$bright_magenta"
cyan = "$bright_cyan"
white = "$bright_white"
]]

-- Transform for contrib/alacritty/lavi.toml
local function transform(compiled)
  return helpers.split_newlines(helpers.apply_template(template, compiled))
end

-- Build the nix structure from compiled colors
local function build_nix_theme(c)
  return {
    colors = {
      primary = {
        background = c.bg,
        foreground = c.fg,
        dim_foreground = c.fg_dim,
        bright_foreground = c.fg_bright,
      },
      cursor = {
        text = c.cursor_fg,
        cursor = c.cursor_bg,
      },
      vi_mode_cursor = {
        text = c.cursor_fg,
        cursor = c.cursor_bg,
      },
      search = {
        matches = { foreground = c.blush, background = c.bg },
        focused_match = { foreground = c.bg, background = c.blush },
      },
      footer_bar = {
        foreground = c.fg,
        background = c.bg_bright,
      },
      hints = {
        start = { foreground = c.med_violet, background = c.bg_bright },
        ["end"] = { foreground = c.fg, background = c.bg_bright },
      },
      selection = {
        text = c.selection_fg,
        background = c.selection_bg,
      },
      normal = {
        black = c.black,
        red = c.red,
        green = c.green,
        yellow = c.yellow,
        blue = c.blue,
        magenta = c.magenta,
        cyan = c.cyan,
        white = c.white,
      },
      bright = {
        black = c.bright_black,
        red = c.bright_red,
        green = c.bright_green,
        yellow = c.bright_yellow,
        blue = c.bright_blue,
        magenta = c.bright_magenta,
        cyan = c.bright_cyan,
        white = c.bright_white,
      },
    },
  }
end

-- Transform for nix/themes/alacritty.nix
local function transform_nix(compiled)
  local theme = build_nix_theme(compiled)
  return transforms.to_nix(theme, {
    header = {
      "Auto-generated by build.lua - do not edit manually",
      "For use with home-manager's programs.alacritty.settings",
    },
  })
end

return {
  colors = colors,
  transform = transform,
  transform_nix = transform_nix,
}
