[colors]
foreground = "#EDE7FE"
background = "#25213B"
cursor_fg = "#EDE7FE"
cursor_bg = "#25213B"
cursor_border = "#463E6F"
selection_fg = "#EDE7FE"
selection_bg = "#584F8C"
ansi = ["#2E2A37", "#E56179", "#6DE38B", "#F8C772", "#7C89F8", "#B09CED", "#33D7B0", "#EEE5FF"]
brights = ["#8876A7", "#ED788D", "#84EB9E", "#F9D494", "#8893FC", "#C09CF7", "#51E1C0", "#FFFFFF"]
