# Auto-generated by build.lua - do not edit manually
# For use with home-manager's programs.alacritty.settings
{
  colors = {
    bright = {
      black = "#8876A7";
      blue = "#8893FC";
      cyan = "#51E1C0";
      green = "#84EB9E";
      magenta = "#C09CF7";
      red = "#ED788D";
      white = "#FFFFFF";
      yellow = "#F9D494";
    };
    cursor = {
      cursor = "#25213B";
      text = "#EDE7FE";
    };
    footer_bar = {
      background = "#463E6F";
      foreground = "#EDE7FE";
    };
    hints = {
      "end" = {
        background = "#463E6F";
        foreground = "#EDE7FE";
      };
      start = {
        background = "#463E6F";
        foreground = "#9487F8";
      };
    };
    normal = {
      black = "#2E2A37";
      blue = "#7C89F8";
      cyan = "#33D7B0";
      green = "#6DE38B";
      magenta = "#B09CED";
      red = "#E56179";
      white = "#EEE5FF";
      yellow = "#F8C772";
    };
    primary = {
      background = "#25213B";
      bright_foreground = "#FFFFFF";
      dim_foreground = "#DED3FD";
      foreground = "#EDE7FE";
    };
    search = {
      focused_match = {
        background = "#EAB9F9";
        foreground = "#25213B";
      };
      matches = {
        background = "#25213B";
        foreground = "#EAB9F9";
      };
    };
    selection = {
      background = "#584F8C";
      text = "#EDE7FE";
    };
    vi_mode_cursor = {
      cursor = "#25213B";
      text = "#EDE7FE";
    };
  };
}
