# vim:ft=kitty
foreground                      #EDE7FE
background                      #25213B
selection_foreground            #EDE7FE
selection_background            #584F8C
# Cursor colors
cursor                          #25213B
cursor_text_color               #EDE7FE
# URL underline color when hovering with mouse
# kitty window border colors
# OS Window titlebar colors
# Tab bar colors
# Colors for marks (marked text in the terminal)
# The basic 16 colors
# black
color0 #2E2A37
color8 #8876A7
# red
color1 #E56179
color9 #ED788D
# green
color2  #6DE38B
color10 #84EB9E
# yellow
color3  #F8C772
color11 #F9D494
# blue
color4  #7C89F8
color12 #8893FC
# magenta
color5  #B09CED
color13 #C09CF7
# cyan
color6  #33D7B0
color14 #51E1C0
# white
color7  #EEE5FF
color15 #FFFFFF
# You can set the remaining 240 colors as color16 to color255.
